### ISSUE TITLE
Compatibility w/ 10.11 (El Capitan)

### ISSUE THREAD

**Issue by mewza** [insidegui/GRProKit#20]
hi !   

is there any way to "hack" the GRProKit to be little more compatible with 10.11 El Capitan?
Up to 10.10 everything was fine, but now corners don't draw, the window bottom corners aren't round, during minimization the window titlebar area becomes transparent temporarily, title text doesn't draw at all, and of course would be nice to use standard minimize/zoom icons instead of custom (although thats not a big issue).

BTW, to make the RoundedBox bezier appear more smoother, you can do this in drawRect:

```
[bgPath appendBezierPathWithRoundedRect:NSMakeRect(minX+0.5, minY+0.5, maxX-1, maxY-1) xRadius:6 yRadius:6];
[bgPath closePath];
```

note: added 0.5 and subtracted 1 from max values.

Other than that, I love the GRProKit and use it religiously :)
<img width="583" alt="screen shot 2015-10-06 at 5 16 03 pm" src="https://cloud.githubusercontent.com/assets/4809989/10326300/62d7284c-6c4e-11e5-8682-100d9a760b17.png">

**Comment by insidegui** [comment]
I'm currently working on an update ;)

**Comment by mewza** [comment]
> On Oct 6, 2015, at 5:27 PM, Guilherme Rambo <notifications@github.com> wrote:
> 
> I'm currently working on an update ;)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/insidegui/GRProKit/issues/20#issuecomment-146043214>.
> 

Could you send ? :)   look forward!


dmitry

**Comment by insidegui** [comment]
I just pushed a little patch to fix this issue with textured windows ;)

**Comment by mewza** [comment]
looks great! thanks for fixing that. :)

**Comment by mewza** [comment]
With the latest submitted version for some reason _customTitleCell
isn’t drawing title on El Capitan. Is that happening to you?

**Comment by mewza** [comment]
another weird issue I am getting is this : (in debugger Console there keeps showing up this message)

2015-10-07 13:15:50.466 Orb[5118:11972255] NSWindow warning: adding an unknown subview: <GRProThemeWidget: 0x6180001615c0>. Break on NSLog to debug.
2015-10-07 13:15:50.467 Orb[5118:11972255] Call stack:
(
	0   AppKit                              0x00007fff944e4285 -[NSThemeFrame addSubview:] + 107
	1   Orb                                 0x000000010001276a -[GRProWindow layoutTrafficLights] + 922
	2   Orb                                 0x00000001000121be -[GRProWindow initWithContentRect:styleMask:backing:defer:] + 430
	3   AppKit                              0x00007fff944ceddf -[NSWindowTemplate nibInstantiate] + 559
	4   AppKit                              0x00007fff944ceb29 -[NSIBObjectData instantiateObject:] + 309
	5   AppKit                              0x00007fff944ce147 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 428
	6   AppKit                              0x00007fff944ac70f loadNib + 384
	7   AppKit                              0x00007fff944abc0e +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 300
	8   AppKit                              0x00007fff944ab9d7 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	9   AppKit                              0x00007fff944ab7a3 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
	10  AppKit                              0x00007fff944a5e3a NSApplicationMain + 466
	11  Orb                                 0x0000000100009ba2 main + 34
	12  Orb                                 0x0000000100001644 start + 52
	13  ???                                 0x0000000000000003 0x0 + 3
)
